# Generated by Django 2.1.5 on 2021-07-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20210729_2155'),
        ('rango', '0002_auto_20210729_2316'),
    ]

    operations = [
    ]
